version: "3.9"

services:
  #  PostgreSQL
  database-postgres:
    image: postgres:14
    container_name: postgresDB
    environment:
      - POSTGRES_DB=logging_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432